### ISSUE TITLE
Default camera nam

### ISSUE THREAD

**Issue by jangirrishabh** [yusukeurakami/mujoco_toolkit#1]
Hi great work on the conversion. Do you know what is the name of the default camera in mujoco?
 intend to use the default camera rather than adding a new one, and thus knowing the name seems necessary for your code to work, thank

**Comment by yusukeurakami** [comment]
Hi @jangirrishabh
Does the default camera mean the free camera that you can rotate during the "./simulate"? In my understanding, they don't have its name. 
If you already have your own camera in the xml, just add the name to it. You don't have to add a new camera to the environment. In my understanding, if you don't have any camera in your environment, you cannot render the image.

**Comment by jangirrishabh** [comment]
Hi @yusukeurakami , thanks that answers my question, the free camera does not have a name to it, so adding another camera is the only option.
I did that, but when rendering via, viewer.render() the images that show up are from the free camera, did you need to change something in order to get the new camera in effect?
PS: I'm using mujoco-py library

**Comment by yusukeurakami** [comment]
@jangirrishabh 
Use env.render() or env.sim.render() instead of viewer.render(). It will take more useful arguments.
https://github.com/openai/gym/blob/2c53496e2c0aa4bc8abae5bd753a7bf30866651a/gym/envs/mujoco/mujoco_env.py#L127
You can choose the camera by name with this function.
(You have to create a viewer object beforehand to render using this. Also, it might require some environment variables)

**Comment by jangirrishabh** [comment]
@yusukeurakami  Your implementation works perfectly, thank you !
